export enum LanguageKey {
  MULTI = "MULTI",
  ARABIC = "ARABIC",
  BENGALI = "BENGALI",
  BULGARIAN = "BULGARIAN",
  BURMESE = "BURMESE",
  CATALAN = "CATALAN",
  CHINESE_SIMP = "CHINESE_SIMP",
  CHINESE_TRAD = "CHINESE_TRAD",
  CZECH = "CZECH",
  DANISH = "DANISH",
  DUTCH = "DUTCH",
  ENGLISH = "ENGLISH",
  FILIPINO = "FILIPINO",
  FINNISH = "FINNISH",
  FRENCH = "FRENCH",
  GERMAN = "GERMAN",
  GREEK = "GREEK",
  HEBREW = "HEBREW",
  HINDI = "HINDI",
  HUNGARIAN = "HUNGARIAN",
  INDONESIAN = "INDONESIAN",
  ITALIAN = "ITALIAN",
  JAPANESE = "JAPANESE",
  KOREAN = "KOREAN",
  LITHUANIAN = "LITHUANIAN",
  MALAY = "MALAY",
  MONGOLIAN = "MONGOLIAN",
  PERSIAN = "PERSIAN",
  POLISH = "POLISH",
  PORTUGUESE_BR = "PORTUGUESE_BR",
  PORTUGUESE_PT = "PORTUGUESE_PT",
  ROMANIAN = "ROMANIAN",
  RUSSIAN = "RUSSIAN",
  SERBO_CROATIAN = "SERBO_CROATIAN",
  SPANISH_ES = "SPANISH_ES",
  SPANISH_LATAM = "SPANISH_LATAM",
  SWEDISH = "SWEDISH",
  THAI = "THAI",
  TURKISH = "TURKISH",
  UKRAINIAN = "UKRAINIAN",
  VIETNAMESE = "VIETNAMESE",
}

export enum SeriesStatus {
  ONGOING = "Ongoing",
  COMPLETED = "Completed",
  CANCELLED = "Cancelled",
}

export enum SettingType {
  STRING = "STRING",
  STRING_ARRAY = "STRING_ARRAY",
  BOOLEAN = "BOOLEAN",
  BOOLEAN_ARRAY = "BOOLEAN_ARRAY",
  NUMBER = "NUMBER",
  NUMBER_ARRAY = "NUMBER_ARRAY",
  LANGUAGE_KEY = "LANGUAGE_KEY",
  LANGUAGE_KEY_ARRAY = "LANGUAGE_KEY_ARRAY",
}

export enum TriState {
  IGNORE = 0,
  INCLUDE = 1,
  EXCLUDE = 2,
}

export enum SortDirection {
  ASCENDING = 0,
  DESCENDING = 1,
}

export enum ExternalClient {
  TACHIYOMI = "tachiyomi",
}
