import { LanguageKey } from "./enums";
import { Language } from "./types";

// eslint-disable-next-line import/prefer-default-export
export const Languages: { [key: string]: Language } = {
  [LanguageKey.MULTI]: {
    key: LanguageKey.MULTI,
    name: "Multi",
    flagCode: "",
    iso639_1: "",
  },
  [LanguageKey.ARABIC]: {
    key: LanguageKey.ARABIC,
    name: "Arabic",
    flagCode: "sa",
    iso639_1: "ar",
  },
  [LanguageKey.BENGALI]: {
    key: LanguageKey.BENGALI,
    name: "Bengali",
    flagCode: "bd",
    iso639_1: "bn",
  },
  [LanguageKey.BULGARIAN]: {
    key: LanguageKey.BULGARIAN,
    name: "Bulgarian",
    flagCode: "bg",
    iso639_1: "bg",
  },
  [LanguageKey.BURMESE]: {
    key: LanguageKey.BURMESE,
    name: "Burmese",
    flagCode: "mm",
    iso639_1: "my",
  },
  [LanguageKey.CATALAN]: {
    key: LanguageKey.CATALAN,
    name: "Catalan",
    flagCode: "ct",
    iso639_1: "ca",
  },
  [LanguageKey.CHINESE_SIMP]: {
    key: LanguageKey.CHINESE_SIMP,
    name: "Chinese (simplified)",
    flagCode: "cn",
    iso639_1: "zh",
  },
  [LanguageKey.CHINESE_TRAD]: {
    key: LanguageKey.CHINESE_TRAD,
    name: "Chinese (traditional)",
    flagCode: "hk",
    iso639_1: "zh",
  },
  [LanguageKey.CZECH]: {
    key: LanguageKey.CZECH,
    name: "Czech",
    flagCode: "cz",
    iso639_1: "cs",
  },
  [LanguageKey.DANISH]: {
    key: LanguageKey.DANISH,
    name: "Danish",
    flagCode: "dk",
    iso639_1: "da",
  },
  [LanguageKey.DUTCH]: {
    key: LanguageKey.DUTCH,
    name: "Dutch",
    flagCode: "nl",
    iso639_1: "nl",
  },
  [LanguageKey.ENGLISH]: {
    key: LanguageKey.ENGLISH,
    name: "English",
    flagCode: "gb",
    iso639_1: "en",
  },
  [LanguageKey.FILIPINO]: {
    key: LanguageKey.FILIPINO,
    name: "Filipino",
    flagCode: "ph",
    iso639_1: "tl",
  },
  [LanguageKey.FINNISH]: {
    key: LanguageKey.FINNISH,
    name: "Finnish",
    flagCode: "fi",
    iso639_1: "fi",
  },
  [LanguageKey.FRENCH]: {
    key: LanguageKey.FRENCH,
    name: "French",
    flagCode: "fr",
    iso639_1: "fr",
  },
  [LanguageKey.GERMAN]: {
    key: LanguageKey.GERMAN,
    name: "German",
    flagCode: "de",
    iso639_1: "de",
  },
  [LanguageKey.GREEK]: {
    key: LanguageKey.GREEK,
    name: "Greek",
    flagCode: "gr",
    iso639_1: "el",
  },
  [LanguageKey.HEBREW]: {
    key: LanguageKey.HEBREW,
    name: "Hebrew",
    flagCode: "il",
    iso639_1: "he",
  },
  [LanguageKey.HINDI]: {
    key: LanguageKey.HINDI,
    name: "Hindi",
    flagCode: "in",
    iso639_1: "hi",
  },
  [LanguageKey.HUNGARIAN]: {
    key: LanguageKey.HUNGARIAN,
    name: "Hungarian",
    flagCode: "hu",
    iso639_1: "hu",
  },
  [LanguageKey.INDONESIAN]: {
    key: LanguageKey.INDONESIAN,
    name: "Indonesian",
    flagCode: "id",
    iso639_1: "id",
  },
  [LanguageKey.ITALIAN]: {
    key: LanguageKey.ITALIAN,
    name: "Italian",
    flagCode: "it",
    iso639_1: "it",
  },
  [LanguageKey.JAPANESE]: {
    key: LanguageKey.JAPANESE,
    name: "Japanese",
    flagCode: "jp",
    iso639_1: "jp",
  },
  [LanguageKey.KOREAN]: {
    key: LanguageKey.KOREAN,
    name: "Korean",
    flagCode: "kr",
    iso639_1: "ko",
  },
  [LanguageKey.LITHUANIAN]: {
    key: LanguageKey.LITHUANIAN,
    name: "Lithuanian",
    flagCode: "lt",
    iso639_1: "lt",
  },
  [LanguageKey.MALAY]: {
    key: LanguageKey.MALAY,
    name: "Malay",
    flagCode: "my",
    iso639_1: "ms",
  },
  [LanguageKey.MONGOLIAN]: {
    key: LanguageKey.MONGOLIAN,
    name: "Mongolian",
    flagCode: "mn",
    iso639_1: "mn",
  },
  [LanguageKey.PERSIAN]: {
    key: LanguageKey.PERSIAN,
    name: "Persian",
    flagCode: "ir",
    iso639_1: "fa",
  },
  [LanguageKey.POLISH]: {
    key: LanguageKey.POLISH,
    name: "Polish",
    flagCode: "pl",
    iso639_1: "pl",
  },
  [LanguageKey.PORTUGUESE_BR]: {
    key: LanguageKey.PORTUGUESE_BR,
    name: "Portuguese (BR)",
    flagCode: "br",
    iso639_1: "pt",
  },
  [LanguageKey.PORTUGUESE_PT]: {
    key: LanguageKey.PORTUGUESE_PT,
    name: "Portuguese (PT)",
    flagCode: "pt",
    iso639_1: "pt",
  },
  [LanguageKey.ROMANIAN]: {
    key: LanguageKey.ROMANIAN,
    name: "Romanian",
    flagCode: "ro",
    iso639_1: "ro",
  },
  [LanguageKey.RUSSIAN]: {
    key: LanguageKey.RUSSIAN,
    name: "Russian",
    flagCode: "ru",
    iso639_1: "ru",
  },
  [LanguageKey.SERBO_CROATIAN]: {
    key: LanguageKey.SERBO_CROATIAN,
    name: "Serbo-Croatian",
    flagCode: "rs",
    iso639_1: "sr",
  },
  [LanguageKey.SPANISH_ES]: {
    key: LanguageKey.SPANISH_ES,
    name: "Spanish (ES)",
    flagCode: "es",
    iso639_1: "es",
  },
  [LanguageKey.SPANISH_LATAM]: {
    key: LanguageKey.SPANISH_LATAM,
    name: "Spanish (LATAM)",
    flagCode: "mx",
    iso639_1: "es",
  },
  [LanguageKey.SWEDISH]: {
    key: LanguageKey.SWEDISH,
    name: "Swedish",
    flagCode: "se",
    iso639_1: "sv",
  },
  [LanguageKey.THAI]: {
    key: LanguageKey.THAI,
    name: "Thai",
    flagCode: "th",
    iso639_1: "th",
  },
  [LanguageKey.TURKISH]: {
    key: LanguageKey.TURKISH,
    name: "Turkish",
    flagCode: "tr",
    iso639_1: "tr",
  },
  [LanguageKey.UKRAINIAN]: {
    key: LanguageKey.UKRAINIAN,
    name: "Ukrainian",
    flagCode: "ua",
    iso639_1: "uk",
  },
  [LanguageKey.VIETNAMESE]: {
    key: LanguageKey.VIETNAMESE,
    name: "Vietnamese",
    flagCode: "vn",
    iso639_1: "vi",
  },
};
